# WordMesh Backend - 开发环境配置

[database]
username = "wordmesh"
password = "wordmesh123"
host = "localhost"
port = 5432
database_name = "wordmesh_dev"
max_connections = 5
connect_timeout_seconds = 5

[neo4j]
uri = "bolt://localhost:7687"
username = "neo4j"
password = "wordmesh123"

[application]
host = "127.0.0.1"
port = 8080

[jwt]
secret = "dev-secret-key-not-for-production"
issuer = "wordmesh-backend"
access_token_ttl_minutes = 60
refresh_token_ttl_hours = 24

[auth]
enabled = true

[auth.jwt]
algorithm = "HS256"
access_ttl_secs = 3600
refresh_ttl_secs = 604800
secret = "dev-auth-secret"  # 开发环境使用对称密钥

[auth.password]
min_length = 8
require_complexity = false

[logging]
level = "debug"