# WordMesh Backend - 测试环境配置

[database]
username = "postgres"
password = "Shicong666"
host = "localhost"
port = 5432
database_name = "wordmesh"
max_connections = 5
connect_timeout_seconds = 5

[neo4j]
uri = "bolt://localhost:7688"
username = "neo4j"
password = "test123"

[application]
host = "127.0.0.1"
port = 8081

[jwt]
secret = "test-secret-key"
issuer = "wordmesh-backend"
access_token_ttl_minutes = 30
refresh_token_ttl_hours = 1

[auth]
enabled = true

[auth.jwt]
algorithm = "HS256"
access_ttl_secs = 900  # 测试环境缩短有效期便于验证
refresh_ttl_secs = 1800
secret = "test-auth-secret"

[auth.password]
min_length = 8
require_complexity = false

[logging]
level = "warn"
